POST http://localhost:3000/productImport

######

POST http://localhost:3000/productImport
Content-Type: application/json

{
  "productType": {
    "typeId": "product-type",
    "id": "1b4e7db5-51a6-4761-9c00-f466cd3d4c08"
  },
  "name": {
    "en": "Sample T-Shirt 2"
  },
  "slug": {
    "en": "sample-t-shirt-2"
  },
  "description": {
    "en": "A comfortable cotton t-shirt in multiple sizes."
  },
  "key": "tshirt-2",
  "masterVariant": {
    "sku": "TSHIRT-001-1",
    "prices": [
      {
        "value": {
          "currencyCode": "EUR",
          "centAmount": 1999
        }
      }
    ]
  },
  "variants": [
    {
      "sku": "TSHIRT-002-2",
      "prices": [
        {
          "value": {
            "currencyCode": "EUR",
            "centAmount": 1999
          }
        }
      ]
    }
  ],
  "publish": true
}


####
POST https://service-j2h831kz8pjqjfekatjuwigx.europe-west1.gcp.3.sandbox.commercetools.app/productImport


###

POST https://service-j2h831kz8pjqjfekatjuwigx.europe-west1.gcp.3.sandbox.commercetools.app/productImport
Content-Type: application/json

{
  "productType": {
    "typeId": "product-type",
    "id": "1b4e7db5-51a6-4761-9c00-f466cd3d4c08"
  },
  "name": {
    "en": "Connector APP Product"
  },
  "slug": {
    "en": "conn-app-tshirt"
  },
  "description": {
    "en": "I was created through the app. "
  },
  "key": "conn-app-tshirt",
  "masterVariant": {
    "sku": "TSHIRT-001-3",
    "prices": [
      {
        "value": {
          "currencyCode": "EUR",
          "centAmount": 1999
        }
      }
    ]
  },
  "variants": [
    {
      "sku": "TSHIRT-002-4",
      "prices": [
        {
          "value": {
            "currencyCode": "EUR",
            "centAmount": 1999
          }
        }
      ]
    }
  ],
  "publish": true
}