# curl -X POST
#  https://auth.europe-west1.gcp.commercetools.com/oauth/token
#  -H "Content-Type: application/x-www-form-urlencoded"
#  -u "<clientId>:<clientSecret>"
#  -d "grant_type=client_credentials&scope=<scope>"
POST https://auth.europe-west1.gcp.commercetools.com/oauth/token
Authorization: Basic 0h3yIrifAM3OUJAFGmjRhgo- qBGXStmjQux_PEq6VcgbWASjiBg7xDuy
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials &
scope = manage_project:poc-witt-001

> {% client.global.set("bearerToken", response.body.access_token); %}

###


// create the connectorStaged
POST https://connect.europe-west1.gcp.commercetools.com/connectors/drafts
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "key": "productimportconnector",
  "name": "ProductImportConnector",
  "description": "An example connector",
  "creator": {
    "title": "",
    "name": "Bjorna Kalaja",
    "email": "bjke@foryoundyourcustomers.com",
    "company": "foryoundyourcustomers",
    "noOfDevelopers": 10
  },
  "repository": {
    "url": "https://github.com/bjornak3/witt-poc-ct-import.git",
    "tag": "1.1.3"
  },
  "supportedRegions" : ["europe-west1.gcp"]
}

####

POST https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=productimportconnector
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "version": 21,
  "actions": [
    {
      "action": "setRepository",
      "url": "https://github.com/bjornak3/witt-poc-ct-import.git",
      "tag": "1.1.3"
    }
  ]
}


####
//check status of connector

POST https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=productimportconnector
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "version": 25,
  "actions": [
    {
      "action": "updatePreviewable"
    }
  ]
}



####

// publish connector

POST https://connect.europe-west1.gcp.commercetools.com/connectors/drafts/key=productimportconnector
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "version": 25,
  "actions": [
    {
      "action": "publish",
      "certification": false
    }
  ]
}



######

// get published connector

GET https://connect.europe-west1.gcp.commercetools.com/connectors/key=productimportconnector
Authorization: Bearer {{bearerToken}}

